// Styles
import './styles/main.scss'

// Components
export { default as UiAccordion } from './components/UiAccordion/UiAccordion.vue'
export { default as UiAccordionItem } from './components/UiAccordion/UiAccordionItem.vue'
export { default as UiAlert } from './components/UiAlert/UiAlert.vue'
export { default as UiAvatar } from './components/UiAvatar/UiAvatar.vue'
export { default as UiBadge } from './components/UiBadge/UiBadge.vue'
export { default as UiButton } from './components/UiButton/UiButton.vue'
export { default as UiButtonGroup } from './components/UiButtonGroup/UiButtonGroup.vue'
export { default as UiCard } from './components/UiCard/UiCard.vue'
export { default as UiChatArea } from './components/UiChatArea/UiChatArea.vue'
export { default as UiChatContainer } from './components/UiChatContainer/UiChatContainer.vue'
export { default as UiCheckbox } from './components/UiCheckbox/UiCheckbox.vue'
export { default as UiDropdown } from './components/UiDropdown/UiDropdown.vue'
export { default as UiDropdownTrigger } from './components/UiDropdown/UiDropdownTrigger.vue'
export { default as UiDropdownMenu } from './components/UiDropdown/UiDropdownMenu.vue'
export { default as UiDropdownItem } from './components/UiDropdown/UiDropdownItem.vue'
export { default as UiDropdownSeparator } from './components/UiDropdown/UiDropdownSeparator.vue'
export { default as UiFieldset } from './components/UiFieldset/UiFieldset.vue'
export { default as UiFileInput } from './components/UiFileInput/UiFileInput.vue'
export { default as UiFormField } from './components/UiFormField/UiFormField.vue'
export { default as UiImage } from './components/UiImage/UiImage.vue'
export { default as UiInput } from './components/UiInput/UiInput.vue'
export { default as UiInputGroup } from './components/UiInputGroup/UiInputGroup.vue'
export { default as UiInputGroupText } from './components/UiInputGroup/UiInputGroupText.vue'
export { default as UiLabel } from './components/UiLabel/UiLabel.vue'
export { default as UiLightbox } from './components/UiLightbox/UiLightbox.vue'
export { default as UiMessage } from './components/UiMessage/UiMessage.vue'
export { default as UiModal } from './components/UiModal/UiModal.vue'
export { default as UiNav } from './components/UiNav/UiNav.vue'
export { default as UiNavGroup } from './components/UiNav/UiNavGroup.vue'
export { default as UiNavItem } from './components/UiNav/UiNavItem.vue'
export { default as UiRadio } from './components/UiRadio/UiRadio.vue'
export { default as UiSelect } from './components/UiSelect/UiSelect.vue'
export { default as UiSlider } from './components/UiSlider/UiSlider.vue'
export { default as UiStack } from './components/UiStack/UiStack.vue'
export { default as UiTabs } from './components/UiTabs/UiTabs.vue'
export { default as UiTabList } from './components/UiTabs/UiTabList.vue'
export { default as UiTabTrigger } from './components/UiTabs/UiTabTrigger.vue'
export { default as UiTabPanel } from './components/UiTabs/UiTabPanel.vue'
export { default as UiTextarea } from './components/UiTextarea/UiTextarea.vue'
export { default as UiUserCard } from './components/UiUserCard/UiUserCard.vue'

// Types
export type { AlertVariant } from './components/UiAlert/UiAlert.vue'
export type { AvatarSize, AvatarShape } from './components/UiAvatar/UiAvatar.vue'
export type { ButtonGroupOrientation } from './components/UiButtonGroup/UiButtonGroup.vue'
export type { CardVariant, CardRadius, CardShadow, CardPadding } from './components/UiCard/UiCard.vue'
export type { FieldsetVariant } from './components/UiFieldset/UiFieldset.vue'
export type { ImageFit, ImageRadius } from './components/UiImage/UiImage.vue'
export type { LightboxItem } from './components/UiLightbox/UiLightbox.vue'
export type { MessageVariant } from './components/UiMessage/UiMessage.vue'
export type { SelectOption, SelectOptionGroup, SelectOptionOrGroup } from './components/UiSelect/UiSelect.vue'
export type { StackDirection, StackGap, StackAlign, StackJustify, StackWrap } from './components/UiStack/UiStack.vue'
export type { UserCardLayout, UserCardSize, UserCardBadge } from './components/UiUserCard/UiUserCard.vue'
export type { Size, Variant, Status } from './types'

// Composables
export { useDisclosure } from './composables'
export type { UseDisclosureOptions, UseDisclosureReturn } from './composables'

// Icons (re-export commonly used)
export * from './icons'
